### ISSUE TITLE
Bug in Line no 67 in customer.java

### ISSUE THREAD

**Issue by Gopinath-gi** [Gopinath-gi/wiproappproject#1]
Hi Bipeen,

Please look into the bug asap. Please let me know if any issues.

**Comment by bipeensinha** [comment]
I am working on it , in the meantine can also ask Rajesh to sned me library file

**Comment by Gopinath-gi** [comment]
ok I will ask Rajesh to send you the library file.

**Comment by bipeensinha** [comment]
Hi Team , i have foixed thios issues now
![a](https://user-images.githubusercontent.com/49720823/108806619-33543e00-75c8-11eb-90d5-472654ae5f69.png)

**Comment by Gopinath-gi** [comment]
Thank you so much. Please close the issues.

**Comment by bipeensinha** [comment]
![CDNdemo](https://user-images.githubusercontent.com/49720823/108806669-57178400-75c8-11eb-9e11-f6263b6185d4.jpg)
